### ISSUE TITLE
Creative Commons 并不适合作为程序、源码的开源协议

### ISSUE THREAD

**Issue by Sunpeng1995** [fdtemp/SceneEngine#3]
CC主要是知识共享，一般用来作为文档、图片、视频等知识型载体的共享协议。
源码的共享还是推荐去用专门的开源协议，像MIT、GPL、BSD等。

**Comment by Danielhu229** [comment]
同意，我推荐[WTFPL](http://www.wtfpl.net/)
Do What the Fuck You Want to Public License
你他妈想干什么就干什么公共许可证

**Comment by fdtemp** [comment]
给大佬递茶Orz,一直在编shader没看到......
